### ISSUE TITLE
Multiple versions for the template

### ISSUE THREAD

**Issue by robikudor** [Wolfpack-Digital/rails-starter-kit#22]
**Is your feature request related to a problem? Please describe.**
We should have a branch for a template which includes a simple user model with auth.

**Describe the solution you'd like**
Separate the current version and the update version which includes the authentication and authorization of a user model.

**Comment by siklodi-mariusz** [comment]
I would suggest an approach in which the authentication is added based on a conditional so while using the template to start a new project, users should be prompted with a question whether they what user authentication to be set up or not.

**Comment by siklodi-mariusz** [comment]
Implemented in #20 with conditional flag
