### ISSUE TITLE
Add Apipie

### ISSUE THREAD

**Issue by siklodi-mariusz** [Wolfpack-Digital/rails-starter-kit#26]
### Discussed in https://github.com/Wolfpack-Digital/rails-template/discussions/25

<div type='discussions-op-text'>

<sup>Originally posted by **bogdan-boer** March 14, 2022</sup>
Hello, 

Since we are using apipie for documentation for most projects maybe it would be a good idea to do the initial setup in this repo so it won't be done manually for each project setup, what do you think?</div>

**Comment by robikudor** [comment]
I added the apipie-rails gem in this PR. 
https://github.com/Wolfpack-Digital/rails-template/pull/20

**Comment by siklodi-mariusz** [comment]
I've noticed but probably you shouldn't have included it. Please try and keep a PR more focused without including things that are not related to the main goal of the PR.

**Comment by robikudor** [comment]
At that moment I did not know that we will have that many updates in the near future on this template. So I added the issues I faced, when creating a new project. I will remove them from that PR.

**Comment by siklodi-mariusz** [comment]
Fixed in #27
