### ISSUE TITLE
Rails controller generation for api projects

### ISSUE THREAD

**Issue by robikudor** [Wolfpack-Digital/rails-starter-kit#29]
Writing boilerplate code is boring, especially in new projects where you need to create the controller file, and related specs and docs for this. 
Rails has a built in generator for this, but it is not customisable. 

I created a generator for this, which creates the mentioned files and also includes the listed actions and the documentation file in the controller. 
Should we include this generator in this project? This could be handled with a prompt when creating a new project.

**Comment by siklodi-mariusz** [comment]
As of right now, I don't have anything against it. Sounds like a good thing that will save some time to create boilerplate files. Now that being said I would suggest maybe submitting this to a team vote to see what's the consensus. @Wolfpack-Digital/wolfpack-devs  let's keep it simple and add 👍  / 👎  reactions to let us know about your thoughts on this. 

Also, if you feel like you have more time to allocate for working on the template, would you consider working on #19 until this gets sorted? It would be nice to start the new projects with Rails 7.

**Comment by siklodi-mariusz** [comment]
Implemented in #32
